// Code generated by go generate; DO NOT EDIT.

package command

const pupCommandSchemaVersion = "1.6.6"

const pupMaxActionPathWords = 5

var pupKnownActionPaths = pupActionPathSet(`
acp serve
agent guide
agent schema
agentless-scanning aws create
agentless-scanning aws delete
agentless-scanning aws get
agentless-scanning aws list
agentless-scanning aws on-demand create
agentless-scanning aws on-demand get
agentless-scanning aws on-demand list
agentless-scanning aws update
agentless-scanning azure create
agentless-scanning azure delete
agentless-scanning azure get
agentless-scanning azure list
agentless-scanning azure update
agentless-scanning gcp create
agentless-scanning gcp delete
agentless-scanning gcp get
agentless-scanning gcp list
agentless-scanning gcp update
alias delete
alias import
alias list
alias set
api
api-keys create
api-keys delete
api-keys get
api-keys list
apm adaptive-sampling check
apm adaptive-sampling get-allotment
apm adaptive-sampling offboard
apm adaptive-sampling onboard
apm adaptive-sampling onboarding-status
apm adaptive-sampling preview
apm adaptive-sampling set-allotment
apm dependencies list
apm entities list
apm flow-map
apm sampling-rules create
apm sampling-rules delete
apm sampling-rules get
apm sampling-rules list
apm sampling-rules update
apm service-config get
apm service-library-config get
apm service-remapping create
apm service-remapping delete
apm service-remapping get
apm service-remapping list
apm service-remapping update
apm services list
apm services operations
apm services resources
apm services stats
apm troubleshooting list
app-builder create
app-builder delete
app-builder delete-batch
app-builder get
app-builder list
app-builder publish
app-builder unpublish
app-builder update
app-keys create
app-keys delete
app-keys get
app-keys list
app-keys update
audit-logs list
audit-logs search
auth list
auth login
auth logout
auth refresh
auth status
auth test
authn-mappings create
authn-mappings delete
authn-mappings get
authn-mappings list
authn-mappings update
bits ask
cases archive
cases assign
cases comments create
cases comments delete
cases comments get
cases comments list
cases comments update
cases create
cases get
cases jira create-issue
cases jira link
cases jira unlink
cases move
cases projects create
cases projects delete
cases projects get
cases projects list
cases projects notification-rules create
cases projects notification-rules delete
cases projects notification-rules list
cases projects notification-rules update
cases projects update
cases search
cases servicenow create-ticket
cases timeline
cases unarchive
cases update-description
cases update-priority
cases update-status
cases update-title
change-requests create
change-requests create-branch
change-requests decisions delete
change-requests decisions update
change-requests get
change-requests update
change-stories list
cicd dora patch-deployment
cicd events aggregate
cicd events search
cicd flaky-tests search
cicd flaky-tests update
cicd pipelines get
cicd pipelines list
cicd tests aggregate
cicd tests list
cicd tests search
cloud aws list
cloud azure list
cloud gcp list
cloud oci products list
cloud oci tenancies create
cloud oci tenancies delete
cloud oci tenancies get
cloud oci tenancies list
cloud oci tenancies update
code-coverage branch-summary
code-coverage commit-summary
completions
containers images list
containers list
costs anomalies list
costs ccm budgets delete
costs ccm budgets get
costs ccm budgets list
costs ccm budgets upsert
costs ccm budgets validate
costs ccm commitments coverage
costs ccm commitments coverage-ts
costs ccm commitments hotspots
costs ccm commitments list
costs ccm commitments savings
costs ccm commitments savings-ts
costs ccm commitments utilization
costs ccm commitments utilization-ts
costs ccm custom-costs delete
costs ccm custom-costs get
costs ccm custom-costs list
costs ccm custom-costs upload
costs ccm tag-descriptions delete
costs ccm tag-descriptions generate
costs ccm tag-descriptions get
costs ccm tag-descriptions list
costs ccm tag-descriptions upsert
costs ccm tag-keys get
costs ccm tag-keys list
costs ccm tag-metadata currency
costs ccm tag-metadata list
costs ccm tag-metadata metrics
costs ccm tag-metadata orchestrators
costs ccm tag-metadata tag-sources
costs ccm tags list
costs datadog attribution
costs datadog aws-config create
costs datadog aws-config delete
costs datadog aws-config get
costs datadog aws-config list
costs datadog azure-config create
costs datadog azure-config delete
costs datadog azure-config get
costs datadog azure-config list
costs datadog by-org
costs datadog gcp-config create
costs datadog gcp-config delete
costs datadog gcp-config get
costs datadog gcp-config list
costs datadog projected
costs oci-configs list
csm-threats agent-policies create
csm-threats agent-policies delete
csm-threats agent-policies get
csm-threats agent-policies list
csm-threats agent-policies update
csm-threats agent-rules create
csm-threats agent-rules delete
csm-threats agent-rules get
csm-threats agent-rules list
csm-threats agent-rules update
csm-threats backend-rules create
csm-threats backend-rules delete
csm-threats backend-rules get
csm-threats backend-rules list
csm-threats backend-rules update
csm-threats backend-rules validate
csm-threats policy download
dashboards annotations create
dashboards annotations delete
dashboards annotations get-page
dashboards annotations list
dashboards annotations update
dashboards create
dashboards delete
dashboards get
dashboards list
dashboards update
dashboards url
dashboards widgets create
dashboards widgets delete
dashboards widgets get
dashboards widgets list
dashboards widgets update
data-deletion requests cancel
data-deletion requests create
data-deletion requests list
data-governance scanner rules list
datasets create
datasets delete
datasets get
datasets list
datasets update
dbm samples search
ddsql schema columns
ddsql schema tables
ddsql spec
ddsql table
ddsql time-series
debugger context
debugger probes create
debugger probes delete
debugger probes get
debugger probes list
debugger probes watch
deployment-gates evaluations get
deployment-gates evaluations trigger
deployment-gates gates create
deployment-gates gates delete
deployment-gates gates get
deployment-gates gates list
deployment-gates gates update
deployment-gates rules create
deployment-gates rules delete
deployment-gates rules get
deployment-gates rules list
deployment-gates rules update
docs ask
downtime cancel
downtime create
downtime get
downtime list
error-tracking issues get
error-tracking issues search
events get
events list
events post
events search
extension install
extension list
extension list-remote
extension remove
extension upgrade
feature-flags allocations create
feature-flags allocations update
feature-flags disable
feature-flags enable
feature-flags environments create
feature-flags environments delete
feature-flags environments get
feature-flags environments list
feature-flags environments update
feature-flags exposure pause
feature-flags exposure resume
feature-flags exposure start
feature-flags exposure stop
feature-flags flags archive
feature-flags flags create
feature-flags flags get
feature-flags flags list
feature-flags flags unarchive
feature-flags flags update
fleet agents get
fleet agents list
fleet agents tracers
fleet agents versions
fleet deployments cancel
fleet deployments configure
fleet deployments get
fleet deployments list
fleet deployments upgrade
fleet schedules create
fleet schedules delete
fleet schedules get
fleet schedules list
fleet schedules trigger
fleet schedules update
fleet tracers list
format
hamr connections create
hamr connections get
idp assist
idp deps
idp find
idp migrate-schema
idp owner
idp register
incidents attachments delete
incidents attachments list
incidents get
incidents handles create
incidents handles delete
incidents handles list
incidents handles update
incidents import
incidents list
incidents postmortem-templates create
incidents postmortem-templates delete
incidents postmortem-templates get
incidents postmortem-templates list
incidents postmortem-templates update
incidents settings get
incidents settings update
infrastructure hosts get
infrastructure hosts list
integrations aws cloud-auth persona-mappings create
integrations aws cloud-auth persona-mappings delete
integrations aws cloud-auth persona-mappings get
integrations aws cloud-auth persona-mappings list
integrations google-chat handles create
integrations google-chat handles delete
integrations google-chat handles get
integrations google-chat handles list
integrations google-chat handles update
integrations google-chat space-get
integrations jira accounts delete
integrations jira accounts list
integrations jira templates create
integrations jira templates delete
integrations jira templates get
integrations jira templates list
integrations jira templates update
integrations list
integrations ms-teams channel-get
integrations ms-teams handles create
integrations ms-teams handles delete
integrations ms-teams handles get
integrations ms-teams handles list
integrations ms-teams handles update
integrations ms-teams workflows create
integrations ms-teams workflows delete
integrations ms-teams workflows get
integrations ms-teams workflows list
integrations ms-teams workflows update
integrations pagerduty list
integrations servicenow assignment-groups list
integrations servicenow business-services list
integrations servicenow instances list
integrations servicenow templates create
integrations servicenow templates delete
integrations servicenow templates get
integrations servicenow templates list
integrations servicenow templates update
integrations servicenow users list
integrations slack list
integrations webhooks list
investigations get
investigations list
investigations trigger
kafka broker-configs
kafka client-configs
kafka read-messages
kafka subject-schemas
kafka topic-configs
llm-obs annotation-queues create
llm-obs annotation-queues delete
llm-obs annotation-queues interactions add
llm-obs annotation-queues interactions delete
llm-obs annotation-queues interactions list
llm-obs annotation-queues list
llm-obs annotation-queues update
llm-obs datasets batch-update
llm-obs datasets clone
llm-obs datasets create
llm-obs datasets list
llm-obs datasets restore
llm-obs eval-config delete
llm-obs eval-config get
llm-obs eval-config update
llm-obs evals create-or-update
llm-obs evals delete
llm-obs evals get-aggregate-stats
llm-obs evals get-evaluator
llm-obs evals list
llm-obs evals list-by-ml-app
llm-obs experiments create
llm-obs experiments delete
llm-obs experiments dimension-values
llm-obs experiments events get
llm-obs experiments events list
llm-obs experiments list
llm-obs experiments metric-values
llm-obs experiments summary
llm-obs experiments update
llm-obs projects create
llm-obs projects list
llm-obs spans expand
llm-obs spans find-errors
llm-obs spans get-agent-loop
llm-obs spans get-content
llm-obs spans get-details
llm-obs spans get-trace
llm-obs spans search
logs aggregate
logs archives delete
logs archives get
logs archives list
logs custom-destinations get
logs custom-destinations list
logs list
logs metrics delete
logs metrics get
logs metrics list
logs query
logs restriction-queries get
logs restriction-queries list
logs search
logs-restriction create
logs-restriction delete
logs-restriction get
logs-restriction list
logs-restriction roles add
logs-restriction roles list
logs-restriction update
metrics list
metrics metadata get
metrics metadata update
metrics query
metrics search
metrics submit
metrics tags list
metrics timeseries
misc ip-ranges
misc status
model-lab projects artifacts
model-lab projects facet-keys
model-lab projects facet-values
model-lab projects get
model-lab projects list
model-lab projects star
model-lab projects unstar
model-lab runs artifacts
model-lab runs delete
model-lab runs facet-keys
model-lab runs facet-values
model-lab runs get
model-lab runs list
model-lab runs pin
model-lab runs unpin
monitors create
monitors delete
monitors diff
monitors get
monitors list
monitors search
monitors update
network devices get
network devices interfaces
network devices list
network devices tags list
network devices tags update
network flows list
network interfaces list
network interfaces update
network list
notebooks annotations create
notebooks annotations delete
notebooks annotations get-page
notebooks annotations list
notebooks annotations update
notebooks create
notebooks delete
notebooks edit
notebooks get
notebooks list
notebooks update
obs-pipelines create
obs-pipelines delete
obs-pipelines get
obs-pipelines list
obs-pipelines update
obs-pipelines validate
on-call escalation-policies create
on-call escalation-policies delete
on-call escalation-policies get
on-call escalation-policies update
on-call notification-channels create
on-call notification-channels delete
on-call notification-channels get
on-call notification-channels list
on-call notification-rules create
on-call notification-rules delete
on-call notification-rules get
on-call notification-rules list
on-call notification-rules update
on-call pages create
on-call pages get
on-call schedules create
on-call schedules delete
on-call schedules get
on-call schedules update
on-call teams create
on-call teams delete
on-call teams get
on-call teams list
on-call teams memberships add
on-call teams memberships list
on-call teams memberships remove
on-call teams memberships update
on-call teams update
organizations get
organizations list
organizations policies create
organizations policies delete
organizations policies get
organizations policies list
organizations policies update
organizations policy-configs list
organizations policy-overrides create
organizations policy-overrides delete
organizations policy-overrides get
organizations policy-overrides list
organizations policy-overrides update
processes list
product-analytics events send
product-analytics query scalar
product-analytics query timeseries
profiling
reference-tables batch-query
reference-tables create
reference-tables get
reference-tables list
rum aggregate
rum apps create
rum apps delete
rum apps get
rum apps list
rum apps update
rum events
rum heatmaps query
rum metrics create
rum metrics delete
rum metrics get
rum metrics list
rum metrics update
rum playlists get
rum playlists list
rum retention-filters create
rum retention-filters delete
rum retention-filters get
rum retention-filters list
rum retention-filters update
rum sessions list
rum sessions search
runbooks describe
runbooks import
runbooks list
runbooks run
runbooks validate
scorecards campaigns create
scorecards campaigns delete
scorecards campaigns get
scorecards campaigns list
scorecards campaigns update
scorecards list
scorecards outcomes batch-create
scorecards outcomes list
scorecards rules create
scorecards rules delete
scorecards rules list
scorecards rules update
security asm-custom-rules create
security asm-custom-rules delete
security asm-custom-rules get
security asm-custom-rules list
security asm-custom-rules update
security asm-exclusions create
security asm-exclusions delete
security asm-exclusions get
security asm-exclusions list
security asm-exclusions update
security content-packs activate
security content-packs deactivate
security content-packs list
security findings analyze
security findings mute
security findings schema
security findings search
security iocs get
security iocs list
security restriction-policies delete
security restriction-policies get
security restriction-policies update
security risk-scores list
security rules bulk-convert
security rules bulk-export
security rules get
security rules list
security rules to-terraform
security signals investigation-queries
security signals list
security signals suggested-actions
security suppressions create
security suppressions delete
security suppressions get
security suppressions list
security suppressions update
security suppressions validate
security terraform bulk-export
security terraform convert
security terraform export
service-catalog get
service-catalog list
skills install
skills list
skills path
slos create
slos delete
slos get
slos list
slos status
slos update
software-catalog entities delete
software-catalog entities list
software-catalog entities preview
software-catalog entities upsert
software-catalog kinds delete
software-catalog kinds list
software-catalog kinds upsert
software-catalog relations list
static-analysis custom-rules create
static-analysis custom-rules delete
static-analysis custom-rules get
static-analysis custom-rules revision
static-analysis custom-rules revisions
static-analysis custom-rulesets delete
static-analysis custom-rulesets get
static-analysis custom-rulesets update
status-pages components create
status-pages components delete
status-pages components get
status-pages components list
status-pages components update
status-pages degradations create
status-pages degradations delete
status-pages degradations get
status-pages degradations list
status-pages degradations update
status-pages maintenances create
status-pages maintenances get
status-pages maintenances list
status-pages maintenances update
status-pages pages create
status-pages pages delete
status-pages pages get
status-pages pages list
status-pages pages update
status-pages third-party list
symdb search
synthetics downtime create
synthetics downtime delete
synthetics downtime list
synthetics locations list
synthetics multistep get-subtest-parents
synthetics multistep get-subtests
synthetics suites create
synthetics suites delete
synthetics suites get
synthetics suites list
synthetics suites update
synthetics tests get
synthetics tests get-browser-result
synthetics tests get-fast-result
synthetics tests get-result
synthetics tests get-version
synthetics tests list
synthetics tests list-latest-browser-results
synthetics tests list-latest-results
synthetics tests list-versions
synthetics tests poll-results
synthetics tests run
synthetics tests search
tag-policies create
tag-policies delete
tag-policies get
tag-policies list
tag-policies score
tag-policies update
tags add
tags delete
tags get
tags list
tags update
test-optimization flaky-tests policies get
test-optimization flaky-tests policies update
test-optimization flaky-tests search
test-optimization flaky-tests update
test-optimization settings delete
test-optimization settings get
test-optimization settings update
traces aggregate
traces metrics create
traces metrics delete
traces metrics get
traces metrics list
traces metrics update
traces search
usage hourly
usage summary
users get
users list
users roles list
users seats users assign
users seats users list
users seats users unassign
users service-accounts app-keys create
users service-accounts app-keys delete
users service-accounts app-keys get
users service-accounts app-keys list
users service-accounts app-keys update
users service-accounts create
version
workflows connections create
workflows connections delete
workflows connections get
workflows connections update
workflows create
workflows delete
workflows get
workflows instances cancel
workflows instances get
workflows instances list
workflows run
workflows update
`)
