package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
	"strings"
)

type schema struct {
	Version  string    `json:"version"`
	Commands []command `json:"commands"`
}

type command struct {
	FullPath    string    `json:"full_path"`
	Subcommands []command `json:"subcommands"`
}

func main() {
	output := "pup_actions_generated.go"
	if len(os.Args) == 3 && os.Args[1] == "-output" {
		output = os.Args[2]
	} else if len(os.Args) != 1 {
		fatal(fmt.Errorf("usage: gen-pup-actions [-output path]"))
	}

	raw, err := exec.Command("pup", "agent", "schema", "--compact").Output()
	if err != nil {
		fatal(fmt.Errorf("read pup command schema: %w", err))
	}
	var source schema
	if err := json.Unmarshal(raw, &source); err != nil {
		fatal(fmt.Errorf("decode pup command schema: %w", err))
	}

	var paths []string
	maxWords := 0
	for _, command := range source.Commands {
		collectLeafPaths(command, &paths)
	}
	sort.Strings(paths)
	for _, path := range paths {
		if words := len(strings.Fields(path)); words > maxWords {
			maxWords = words
		}
	}

	var generated bytes.Buffer
	generated.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	generated.WriteString("\npackage command\n\n")
	fmt.Fprintf(&generated, "const pupCommandSchemaVersion = %q\n\n", source.Version)
	fmt.Fprintf(&generated, "const pupMaxActionPathWords = %d\n\n", maxWords)
	generated.WriteString("var pupKnownActionPaths = pupActionPathSet(`\n")
	generated.WriteString(strings.Join(paths, "\n"))
	generated.WriteString("\n`)\n")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatal(fmt.Errorf("format generated source: %w", err))
	}
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		fatal(fmt.Errorf("write generated source: %w", err))
	}
}

func collectLeafPaths(current command, paths *[]string) {
	if len(current.Subcommands) == 0 {
		if strings.TrimSpace(current.FullPath) != "" {
			*paths = append(*paths, current.FullPath)
		}
		return
	}
	for _, child := range current.Subcommands {
		collectLeafPaths(child, paths)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
